name: CI
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: CI on python${{ matrix.python }} via ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            python: "3.12"
    env:
      TEUTHOLOGY_SUITE_EXTRA_ARGS: "-N 2"
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt install podman golang-github-containernetworking-plugin-dnsname sqlite3 jq
      - name: Create virtualenv
        run: python3 -m venv venv
      - name: Install
        run: ./venv/bin/pip3 install -e .
      - name: Set owner for /dev/loop-control
        run: sudo chown $(whoami) /dev/loop-control
      - name: Configure
        run: ./venv/bin/ceph-devstack config set containers.postgres.count 0
      - name: Doctor
        run: ./venv/bin/ceph-devstack -v doctor --fix
      - name: Build
        run: ./venv/bin/ceph-devstack -v build
      - name: Create
        run: ./venv/bin/ceph-devstack -v create
      - name: Start
        run: ./venv/bin/ceph-devstack -v start
      - name: Wait
        run: ./venv/bin/ceph-devstack wait teuthology
      - name: Show logs (test parfait gsoc code)
        run: ./venv/bin/ceph-devstack logs
      - name: Show logs (test parfait gsoc code) locate log file
        run: ./venv/bin/ceph-devstack logs --locate
      - name: Show logs (test parfait gsoc code) invalid job ID
        run: ./venv/bin/ceph-devstack logs -j 1
      - name: Show logs (test parfait gsoc code) valid job ID
        run: ./venv/bin/ceph-devstack logs -j 2
      - name: Show logs (test parfait gsoc code) valid job ID
        run: ./venv/bin/ceph-devstack logs -j 3
      - name: Start (second run)
        run: ./venv/bin/ceph-devstack -v start
      - name: Wait (second run)
        run: ./venv/bin/ceph-devstack wait teuthology
      - name: Show logs (second run test parfait gsoc code)
        run: ./venv/bin/ceph-devstack logs
      - name: Show logs (second run test parfait gsoc code) locate log file
        run: ./venv/bin/ceph-devstack logs --locate
      - name: Show logs (second run test parfait gsoc code) valid job ID
        run: ./venv/bin/ceph-devstack logs -j 6
      - name: Dump logs
        if: success() || failure()
        run: podman logs -f teuthology
      - name: Create archive
        if: success() || failure()
        run: |
          mkdir -p /tmp/artifacts
      - name: Dump job data
        if: success() || failure()
        run: |
          podman cp paddles:/paddles/dev.db /tmp/
          sqlite3 /tmp/dev.db ".output stdout" ".mode json" "select * from jobs" | jq | tee /tmp/artifacts/jobs.json
      - name: Upload jobs.json
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: /tmp/artifacts/jobs.json
      - name: Create tarball of log archive
        if: success() || failure()
        run: |
          tar -czf /tmp/artifacts/archive.tar ~/.local/share/ceph-devstack/archive/
      - name: Upload log archive
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: /tmp/artifacts/archive.tar
      - name: Stop
        run: ./venv/bin/ceph-devstack -v stop
      - name: Remove
        run: ./venv/bin/ceph-devstack -v remove
